### Livebox Monitor XXXXX Language module ###



# ################################ LABELS ################################

LABELS = {
	# Main window
	'main': {
		'Terminating threads...': '',
		'Signing in...': ''
	},

	# Device list
	'dlist': {
		'T': '',
		'Name': '',
		'Livebox Name': '',
		'MAC': '',
		'IP': '',
		'Link': '',
		'A': '',
		'Wifi': '',
		'E': '',
		'Rx': '',
		'Tx': '',
		'RxRate': '',
		'TxRate': '',
		'Refresh': '',
		'Device Infos': '',
		'Device Events': '',
		'IPv6...': '',
		'Device List': '',
		'Getting IPv6 Information...': '',
		'Loading device list...': '',
		'<None>': '',
		'Unknown': '',
		'UNKNOWN': ''
	},

	# Device list - IPv6 dialog
	'ipv6': {
		'IPv6 enabled:': '',
		'IPv6 address:': '',
		'IPv6 prefix:': '',
		'Name': '',
		'Livebox Name': '',
		'MAC': '',
		'A': '',
		'IPv4': '',
		'IPv6': '',
		'OK': '',
		'IPv6 Devices': ''
	},

	# Livebox infos
	'info': {
		'Name': '',
		'Rx': '',
		'Tx': '',
		'RxRate': '',
		'TxRate': '',
		'Attribute': '',
		'Value': '',
		'Livebox Infos': '',
		'Internet Infos': '',
		'Wifi Infos': '',
		'LAN Infos': '',
		'ONT Infos': '',
		'VoIP Infos': '',
		'IPTV Infos': '',
		'USB Infos': '',
		'Export...': '',
		'Livebox Stats/Infos': '',
		'Getting Livebox information...': '',
		'Getting Internet information...': '',
		'Getting Wifi information...': '',
		'Getting LAN information...': '',
		'Getting ONT information...': '',
		'Getting VoIP information...': '',
		'Getting IPTV information...': '',
		'Getting USB information...': '',
		'Save File': '',
		'Exporting all information...': '',
		'Livebox Information': '',
		'Model': '',
		'Status': '',
		'Livebox Up Time': '',
		'Manufacturer': '',
		'Manufacturer Model Name': '',
		'Description': '',
		'Serial Number': '',
		'Hardware Version': '',
		'Software Version': '',
		'Rescue Version': '',
		'Modem Firmware Version': '',
		'Orange Firmware Version': '',
		'Spec Version': '',
		'Provisioning Code': '',
		'Country': '',
		'MAC Address': '',
		'External IP Address': '',
		'Number Of Reboots': '',
		'Upgrade Occurred': '',
		'Reset Occurred': '',
		'Restore Occurred': '',
		'Active': '',
		'Last Boot': '',
		'Boot Loader Version': '',
		'Firewall Level': '',
		'Internet Active': '',
		'IPTV Active': '',
		'Telephony Active': '',
		'Time': '',
		'Memory': '',
		'Total Memory': '',
		'Free Memory': '',
		'Internet Information': '',
		'Connection': '',
		'Access Type': '',
		'Username': '',
		'Factory Reset Scheduled': '',
		'Connection Error': '',
		'Offer Type': '',
		'Offer Name': '',
		'IPTV Mode': '',
		'WAN Status': '',
		'Link Status': '',
		'Link Type': '',
		'Protocol': '',
		'GPON State': '',
		'Connection Status': '',
		'Last Connection Error': '',
		'IP Address': '',
		'Remote Gateway': '',
		'DNS Servers': '',
		'IPv6 Address': '',
		'IPv6 Prefix': '',
		'Last Connection': '',
		'Max Down Bit Rate': '',
		'Max Up Bit Rate': '',
		'DHCP Status': '',
		'Subnet Mask': '',
		'IP Routers': '',
		'DHCP Server': '',
		'Renew': '',
		'Authentication': '',
		'Authentication Information': '',
		'Connection Up Time': '',
		'Lease Time': '',
		'Lease Time Remaining': '',
		'VLAN ID': '',
		'MTU': '',
		'Wifi Information': '',
		'Wifi': '',
		'Enabled': '',
		'BGN User Bandwidth': '',
		'Scheduler Enabled': '',
		'Radio Status': '',
		'VAP Status': '',
		'Vendor Name': '',
		'SSID': '',
		'SSID Advertisement': '',
		'Security Mode': '',
		'WEP Key': '',
		'PreShared Key': '',
		'Key Pass Phrase': '',
		'WPS Enabled': '',
		'WPS Methods': '',
		'WPS Self PIN': '',
		'WPS Pairing In Progress': '',
		'MAC Filtering': '',
		'Max Bitrate': '',
		'AP Mode': '',
		'STA Mode': '',
		'WDS Mode': '',
		'WET Mode': '',
		'Frequency Band': '',
		'Channel Bandwidth': '',
		'Standard': '',
		'Channel': '',
		'Auto Channel Supported': '',
		'Auto Channel Enabled': '',
		'Channel Change Reason': '',
		'Max Associated Devices': '',
		'Active Associated Devices': '',
		'Noise': '',
		'Antenna Defect': '',
		'LAN Information': '',
		'DHCPv4': '',
		'DHCPv4 Enabled': '',
		'DHCPv4 Status': '',
		'DHCPv4 Gateway': '',
		'DHCPv4 Start': '',
		'DHCPv4 End': '',
		'DHCPv4 Lease Time': '',
		'DHCPv6': '',
		'DHCPv6 Status': '',
		'LAN': '',
		'Current Bit Rate': '',
		'Max Bit Rate Supported': '',
		'Current Duplex Mode': '',
		'Power Saving Supported': '',
		'Power Saving Enabled': '',
		'ONT Information': '',
		'ONT': '',
		'VEIP PPTP UNI': '',
		'OMCI Is Tm Owner': '',
		'Signal RxPower': '',
		'Signal TxPower': '',
		'Temperature': '',
		'Voltage': '',
		'BIAS': '',
		'Equipment ID': '',
		'Vendor ID': '',
		'Vendor Product Code': '',
		'Pon ID': '',
		'Registration ID': '',
		'ONT Software Version 0': '',
		'ONT Software Version 1': '',
		'ONT Software Version Active': '',
		'ONU State': '',
		'Current Down Bit Rate': '',
		'Current Up Bit Rate': '',
		'VoIP Information': '',
		'VoIP': '',
		'VoIP Enabled': '',
		'{} Enabled': '',
		'{} Status': '',
		'{} Status Info': '',
		'{} Number': '',
		'DECT Information': '',
		'PIN': '',
		'RFPI': '',
		'CAT-iq Version': '',
		'Pairing Status': '',
		'Radio State': '',
		'Repeater Status': '',
		'IPTV Information': '',
		'IPTV Status': '',
		'Multi Screens Status': '',
		'Available': '',
		'Disabled': '',
		'IPTV Config': '',
		'USB Information': '',
		'USB': '',
		'Inactive': '',
		'Unknown USB': '',
		'USB Device Storage': '',
		'Key': '',
		'Device Type': '',
		'First Seen': '',
		'File System': '',
		'Capacity': '',
		'Used Space': '',
		'Names': '',
		'USB Device': '',
		'Location': '',
		'Owner': '',
		'USB Version': '',
		'Device Version': '',
		'Product ID': '',
		'Port': '',
		'Rate': ''
	},

	# Device infos
	'dinfo': {
		'Name': '',
		'MAC': '',
		'Attribute': '',
		'Value': '',
		'Refresh': '',
		'Assign Name...': '',
		'Assign Type...': '',
		'Forget...': '',
		'Block': '',
		'Unblock': '',
		'Device Infos': '',
		'Loading device icons...': '',
		'Getting device information...': '',
		'Key': '',
		'Active': '',
		'Authenticated': '',
		'Blocked': '',
		'First connection': '',
		'Last connection': '',
		'Last changed': '',
		'Source': '',
		'Livebox Name': '',
		'DNS Name': '',
		'Type': '',
		'IPv4 Address': '',
		'IPv6 Address': '',
		'Manufacturer': '',
		'Vendor ID': '',
		'Serial Number': '',
		'Product Class': '',
		'Model Name': '',
		'Software Version': '',
		'Hardware Version': '',
		'DHCP Option 55': '',
		'Full Software Version': '',
		'State': '',
		'Protocol': '',
		'Current Mode': '',
		'Pairing Time': '',
		'Uplink Type': '',
		'Wifi Signal Strength': '',
		'Wifi Signal Noise Ratio': '',
		'Supported Standards': '',
		'Supports 2.4GHz': '',
		'Supports 5GHz': '',
		'Supports 6GHz': ''
	},

	# Device infos - Assign name dialog
	'dname': {
		'Names for [{}] device:': '',
		'Local Name': '',
		'Livebox Name': '',
		'OK': '',
		'Cancel': '',
		'Assign device names': ''
	},

	# Device infos - Assign type dialog
	'dtype': {
		'Type for [{}] device:': '',
		'OK': '',
		'Cancel': '',
		'Assign a device type': ''
	},

	# Events
	'events': {
		'Name': '',
		'MAC': '',
		'Time': '',
		'Reason': '',
		'Attributes': '',
		'Display Event': '',
		'Events': '',
		'Event Entry': ''
	},

	# DHCP
	'dhcp': {
		'Name': '',
		'Domain': '',
		'MAC': '',
		'IP': '',
		'Refresh': '',
		'Add...': '',
		'Delete': '',
		'Attribute': '',
		'Value': '',
		'DHCP Setup...': '',
		'DHCP': '',
		'Getting DHCP bindings...': '',
		'Getting DHCP information...': '',
		'DHCP Home Information': '',
		'DHCPv4': '',
		'DHCPv4 Enabled': '',
		'DHCPv4 Status': '',
		'DHCPv4 Gateway': '',
		'Subnet Mask': '',
		'DHCPv4 Start': '',
		'DHCPv4 End': '',
		'DHCPv4 Lease Time': '',
		'DNS Servers': '',
		'DHCPv6': '',
		'DHCPv6 Status': '',
		'DHCPv6 Prefix': '',
		'DHCP Guest Information': '',
		'Status': '',
		'Lease Time': '',
		'Lease Time Remaining': '',
		'Check Authentication': '',
		'Authentication Information': '',
		'DHCPv4 Sent Options': '',
		'DHCPv4 Received Options': '',
		'DUID': '',
		'Request Addresses': '',
		'Request Prefixes': '',
		'Requested Options': '',
		'DHCPv6 Sent Options': '',
		'DHCPv6 Received Options': ''
	},

	# DHCP - Binding dialog
	'dbinding': {
		'Device:': '',
		'MAC address:': '',
		'Domain:': '',
		'IP address:': '',
		'OK': '',
		'Cancel': '',
		'Add DHCP binding': '',
		'-Unknown-': ''
	},

	# DHCP - Setup dialog
	'dsetup': {
		'DHCP Enabled': '',
		'Livebox IP address:': '',
		'Subnet mask:': '',
		'DHCP start IP:': '',
		'DHCP end IP:': '',
		'OK': '',
		'Cancel': '',
		'DHCP Setup': ''
	},

	# Phone
	'phone': {
		'T': '',
		'Time': '',
		'Number': '',
		'Contact': '',
		'Duration': '',
		'Refresh': '',
		'Delete': '',
		'Delete All...': '',
		'Name': '',
		'Mobile': '',
		'Home': '',
		'Work': '',
		'Ring': '',
		'Add...': '',
		'Edit...': '',
		'Phone Ring': '',
		'Export...': '',
		'Import...': '',
		'Phone': '',
		'Loading phone call list...': '',
		'Export File': '',
		'Livebox Contacts': '',
		'Exporting all contacts...': '',
		'Select files to import': '',
		'Importing contacts...': '',
		'Cannot import file(s): ': '',
		'Loading contact list...': ''
	},

	# Phone - Contact edit
	'pcontact': {
		'First name': '',
		'Name': '',
		'Mobile': '',
		'Home': '',
		'Work': '',
		'Ring tone': '',
		'OK': '',
		'Cancel': '',
		'Contact edition': '',
		'Contact creation': ''
	},

	# Actions
	'actions': {
		'Wifi ON': '',
		'Wifi OFF': '',
		'Guest Wifi ON': '',
		'Guest Wifi OFF': '',
		'Wifi Scheduler ON': '',
		'Wifi Scheduler OFF': '',
		'Show Global Status...': '',
		'Wifi': '',
		'Reboot Livebox...': '',
		'Reboot History...': '',
		'Reboots': '',
		'An Open Source project': '',
		'About': '',
		'Preferences...': '',
		'Change Profile...': '',
		'Setup': '',
		'Raw Device List...': '',
		'Raw Topology...': '',
		'Set Log Level...': '',
		'Debug': '',
		'Quit Application': '',
		'Actions': '',
		'Getting Wifi Global Status...': '',
		'Getting Reboot History...': '',
		'Raw Device List': '',
		'Raw Topology': '',
		'Log level selection': '',
		'Please select a log level:': ''
	},

	# Actions - Reboot history
	'rhistory': {
		'Boot Date': '',
		'Boot Reason': '',
		'Shutdown Date': '',
		'Shutdown Reason': '',
		'OK': '',
		'{} Reboot History': '',
		'Unknown': ''
	},

	# Actions - Wifi global status
	'wglobal': {
		'Interfaces': '',
		'OK': '',
		'Wifi Global Status': '',
		'{} Enabled': '',
		'{} Active': '',
		'Wifi Scheduler': '',
		'{} VAP': '',
		'Guest 2.4GHz': '',
		'Guest 5GHz': '',
		'Error': '',
		'Inactive': '',
		'Not signed': ''
	},

	# Repeater
	'repeater': {
		'Name': '',
		'Rx': '',
		'Tx': '',
		'RxRate': '',
		'TxRate': '',
		'Wifi ON': '',
		'Wifi OFF': '',
		'Wifi Scheduler ON': '',
		'Wifi Scheduler OFF': '',
		'Reboot Repeater...': '',
		'Reboot History...': '',
		'Resign...': '',
		'Actions': '',
		'Attribute': '',
		'Value': '',
		'Repeater Infos': '',
		'Wifi Infos': '',
		'LAN Infos': '',
		'Export...': '',
		'Signing in to repeaters...': '',
		'Wrong repeater password': '',
		'Please enter password for repeater {0} ({1}):': '',
		'Getting repeater information...': '',
		'Getting Wifi information...': '',
		'Getting LAN information...': '',
		'Save File': '',
		'{} Infos.txt': '',
		'Exporting all information...': '',
		'Repeater Information': '',
		'Model Name': '',
		'Repeater Up Time': '',
		'Serial Number': '',
		'Hardware Version': '',
		'Software Version': '',
		'Orange Firmware Version': '',
		'Country': '',
		'Time': '',
		'Wifi Information': '',
		'Wifi': '',
		'Enabled': '',
		'Active': '',
		'Read Only': '',
		'Pairing Status': '',
		'PIN Code': '',
		'Scheduler Enabled': '',
		'Radio Status': '',
		'VAP Status': '',
		'Vendor Name': '',
		'MAC Address': '',
		'SSID': '',
		'SSID Advertisement': '',
		'Security Mode': '',
		'WEP Key': '',
		'PreShared Key': '',
		'Key Pass Phrase': '',
		'WPS Enabled': '',
		'WPS Methods': '',
		'WPS Self PIN': '',
		'WPS Pairing In Progress': '',
		'MAC Filtering': '',
		'Max Bitrate': '',
		'AP Mode': '',
		'STA Mode': '',
		'WDS Mode': '',
		'WET Mode': '',
		'Frequency Band': '',
		'Channel Bandwidth': '',
		'Standard': '',
		'Channel': '',
		'Auto Channel Supported': '',
		'Auto Channel Enabled': '',
		'Channel Change Reason': '',
		'Max Associated Devices': '',
		'Active Associated Devices': '',
		'Noise': '',
		'Antenna Defect': '',
		'LAN Information': '',
		'Link Status': '',
		'Link Type': '',
		'Protocol': '',
		'Connection Status': '',
		'Last Connection Error': '',
		'IP Address': '',
		'Remote Gateway': '',
		'DNS Servers': '',
		'IPv6 Address': '',
		'MTU': '',
		'Link to the Livebox': '',
		'Livebox link Infos': '',
		'Interface': '',
		'LAN': '',
		'Current Bit Rate': '',
		'Max Bit Rate Supported': '',
		'Current Duplex Mode': '',
		'Power Saving Supported': '',
		'Power Saving Enabled': ''
	},

	# Config - Preferences
	'prefs': {
		'Main': '',
		'Add': '',
		'Delete': '',
		'Name': '',
		'Livebox URL': '',
		'Livebox User': '',
		'Filter Devices': '',
		'MacAddr Table File': '',
		'Default': '',
		'Profiles': '',
		'macaddress.io API Key': '',
		'Language': '',
		'Tooltips': '',
		'Intl Phone Code': '',
		'List Header Height': '',
		'List Header Font Size': '',
		'List Line Height': '',
		'List Line Font Size': '',
		'Realtime wifi device statistics': '',
		'Preferences': '',
		'OK': '',
		'Cancel': ''
	},

	# Config - Connection
	'cnx': {
		'Cannot connect to the Livebox.': '',
		'It might be unreachable, in that case just wait.': '',
		'Otherwise, try {0}, {1} or {2}.': '',
		'Livebox URL': '',
		'OK': '',
		'Cancel': '',
		'Livebox connection': ''
	},

	# Config - Signin
	'signin': {
		'User': '',
		'Password': '',
		'OK': '',
		'Cancel': '',
		'Wrong password': ''
	},

	# Config - Select profile
	'sprofile': {
		'Profile selection': '',
		'Please select a profile to use:': '',
		'Associated Livebox MAC:': '',
		'Detected Livebox MAC:': '',
		'New Profile...': '',
		'OK': '',
		'Cancel': '',
		'<None>': '',
		'No Livebox detected at profile\'s URL.': '',
		'Detected MAC will be associated to this profile.': '',
		'Warning: another Livebox is associated to this profile.': '',
		'Create Profile': '',
		'Profile name:': ''
	}

	# Tools
	'tools': {
		'Error': '',
		'Status': '',
		'Please confirm': '',
		'True': '',
		'False': '',
		'OK': ''
	}
}



# ################################ TOOLTIPS ################################

TOOLTIPS = {
	# Main window
	'main': {
		'deviceListTab': '',
		'liveboxInfoTab': '',
		'deviceInfoTab': '',
		'eventsTab': '',
		'dhcpTab': '',
		'phoneTab': '',
		'actionTab': '',
		'repeaterTab': ''
	},

	# Device list
	'dlist': {
		'dlist_Type': '',
		'dlist_Name': '',
		'dlist_LBName': '',
		'dlist_MAC': '',
		'dlist_IP': '',
		'dlist_Link': '',
		'dlist_Active': '',
		'dlist_Wifi': '',
		'dlist_Event': '',
		'dlist_Rx': '',
		'dlist_Tx': '',
		'dlist_RxRate': '',
		'dlist_TxRate': '',
		'refresh': '',
		'deviceInfo': '',
		'deviceEvents': '',
		'ipv6': ''
	},

	# Device list - IPv6 dialog
	'ipv6': {
		'ipv6_Name': '',
		'ipv6_LBName': '',
		'ipv6_MAC': '',
		'ipv6_Active': '',
		'ipv6_IPv4': '',
		'ipv6_IPv6': '',
		'ipv6EnabledLabel': '',
		'ipv6Enabled': '',
		'addrLabel': '',
		'addr': '',
		'prefixLabel': '',
		'prefix': '',
		'ok': ''
	},

	# Livebox infos
	'info': {
		'stats_Name': '',
		'stats_Rx': '',
		'stats_Tx': '',
		'stats_RxRate': '',
		'stats_TxRate': '',
		'alist_Attribute': '',
		'alist_Value': '',
		'liveboxInfo': '',
		'internetInfo': '',
		'wifiInfo': '',
		'lanInfo': '',
		'ontInfo': '',
		'voipInfo': '',
		'iptvInfo': '',
		'usbInfo': '',
		'exportInfo': ''
	},

	# Device infos
	'dinfo': {
		'dlist_Name': '',
		'dlist_MAC': '',
		'alist_Attribute': '',
		'alist_Value': '',
		'refresh': '',
		'assignName': '',
		'assignType': '',
		'forget': '',
		'block': '',
		'unblock': ''
	},

	# Device infos - Assign name dialog
	'dname': {
		'mainLabel': '',
		'nameCheckBox': '',
		'nameEdit': '',
		'liveboxNameCheckBox': '',
		'liveboxNameEdit': '',
		'ok': '',
		'cancel': ''
	},

	# Device infos - Assign type dialog
	'dtype': {
		'mainLabel': '',
		'typeNameCombo': '',
		'typeKeyEdit': '',
		'ok': '',
		'cancel': ''
	},

	# Events
	'events': {
		'dlist_Name': '',
		'dlist_MAC': '',
		'elist_Time': '',
		'elist_Reason': '',
		'elist_Attribute': '',
		'displayEvent': ''
	},

	# DHCP
	'dhcp': {
		'dlist_Name': '',
		'dlist_Domain': '',
		'dlist_MAC': '',
		'dlist_IP': '',
		'alist_Attribute': '',
		'alist_Value': '',
		'refreshBinding': '',
		'addBinding': '',
		'delBinding': '',
		'refreshDhcpAttribute': '',
		'dhcpSetup': ''
	},

	# DHCP - Binding dialog
	'dbinding': {
		'deviceLabel': '',
		'deviceCombo': '',
		'macLabel': '',
		'macEdit': '',
		'domainLabel': '',
		'domainCombo': '',
		'ipLabel': '',
		'ipEdit': '',
		'ok': '',
		'cancel': ''
	},

	# DHCP - Setup dialog
	'dsetup': {
		'enableCheckbox': '',
		'liveboxIpLabel': '',
		'liveboxIpEdit': '',
		'maskLabel': '',
		'maskEdit': '',
		'minLabel': '',
		'minEdit': '',
		'maxLabel': '',
		'maxEdit': '',
		'ok': '',
		'cancel': ''
	},

	# Phone
	'phone': {
		'calist_Type': '',
		'calist_Time': '',
		'calist_Number': '',
		'calist_Contact': '',
		'calist_Duration': '',
		'colist_Name': '',
		'colist_Cell': '',
		'colist_Home': '',
		'colist_Work': '',
		'colist_Ring': '',
		'refreshCall': '',
		'deleteCall': '',
		'deleteAllCalls': '',
		'refreshContact': '',
		'addContact': '',
		'editContact': '',
		'deleteContact': '',
		'deleteAllContacts': '',
		'ringToneCombo': '',
		'phoneRing': '',
		'exportContacts': '',
		'importContacts': ''
	},

	# Phone - Contact edit
	'pcontact': {
		'firstNameLabel': '',
		'firstNameEdit': '',
		'nameLabel': '',
		'nameEdit': '',
		'cellLabel': '',
		'cellEdit': '',
		'homeLabel': '',
		'homeEdit': '',
		'workLabel': '',
		'workEdit': '',
		'ringToneLabel': '',
		'ringToneCombo': '',
		'ok': '',
		'cancel': ''
	},

	# Actions
	'actions': {
		'wifiOn': '',
		'wifiOff': '',
		'guestWifiOn': '',
		'guestWifiOff': '',
		'schedulerOn': '',
		'schedulerOff': '',
		'wifiGlobalStatus': '',
		'wifiGroup': '',
		'rebootLivebox': '',
		'rebootHistory': '',
		'rebootGroup': '',
		'appIcon': '',
		'appName': '',
		'openSourceURL': '',
		'aboutGroup': '',
		'prefs': '',
		'changeProfile': '',
		'setupGroup': '',
		'showRawDeviceList': '',
		'showRawTopology': '',
		'setLogLevel': '',
		'debugGroup': '',
		'quit': ''
	},

	# Actions - Reboot history
	'rhistory': {
		'reboot_BootDate': '',
		'reboot_BootReason': '',
		'reboot_ShutdownDate': '',
		'reboot_ShutdownReason': '',
		'ok': ''
	},

	# Actions - Wifi global status
	'wglobal': {
		'ok': ''
	},

	# Repeater
	'repeater': {
		'stats_Name': '',
		'stats_Rx': '',
		'stats_Tx': '',
		'stats_RxRate': '',
		'stats_TxRate': '',
		'alist_Attribute': '',
		'alist_Value': '',
		'wifiOn': '',
		'wifiOff': '',
		'schedulerOn': '',
		'schedulerOff': '',
		'rebootRepeater': '',
		'rebootHistory': '',
		'resign': '',
		'actionsGroup': '',
		'repeaterInfo': '',
		'wifiInfo': '',
		'lanInfo': '',
		'exportInfo': ''
	},

	# Config - Preferences
	'prefs': {
		'profileList': '',
		'addProfile': '',
		'delProfile': '',
		'profileNameLabel': '',
		'profileNameEdit': '',
		'liveboxUrlLabel': '',
		'liveboxUrlEdit': '',
		'liveboxUserLabel': '',
		'liveboxUserEdit': '',
		'filterDevices': '',
		'macAddrTableFileLabel': '',
		'macAddrTableFileEdit': '',
		'defaultProfile': '',
		'profileGroup': '',
		'languageLabel': '',
		'languageCombo': '',
		'tooltips': '',
		'statsFrequencyLabel': '',
		'statsFrequencyEdit': '',
		'macAddrApiKeyLabel': '',
		'macAddrApiKeyEdit': '',
		'phoneCodeLabel': '',
		'phoneCodeEdit': '',
		'listHeaderHeightLabel': '',
		'listHeaderHeightEdit': '',
		'listHeaderFontSizeLabel': '',
		'listHeaderFontSizeEdit': '',
		'listLineHeightLabel': '',
		'listLineHeightEdit': '',
		'listLineFontSizeLabel': '',
		'listLineFontSize': '',
		'realtimeWifiStats': '',
		'prefsGroup': '',
		'ok': '',
		'cancel': ''
	},

	# Config - Connection
	'cnx': {
		'w1Label': '',
		'w2Label': '',
		'w3Label': '',
		'urlLabel': '',
		'urlEdit': '',
		'ok': '',
		'cancel': ''
	},

	# Config - Signin
	'signin': {
		'userLabel': '',
		'userEdit': '',
		'passwordLabel': '',
		'passwordEdit': '',
		'ok': '',
		'cancel': ''
	},

	# Config - Select profile
	'sprofile': {
		'mainLabel': '',
		'profileCombo': '',
		'assMacLabel': '',
		'assMacValue': '',
		'detMacLabel': '',
		'detMacValue': '',
		'warnLabel': '',
		'createProfile': '',
		'ok': '',
		'cancel': ''
	}
}
